---
title: "EquipmentList"
authors: "Megan Cattau"
# Add your name above
date: "2019"
output: html_document
---

# Equipment List for UAS Fieldwork

This document is a working list of equipment needed for UAS field expeditions using the Phantom 4 Pro for forest ecological applications

## Equipment needed in the field: 

- iPad to operate the mission
-	iPhone as a back-up to operate the mission
-	UAS body
-	UAS batteries x 5
-	Cooler for batteries
-	UAS propeller blades x 8 (4 as back-ups)
-	UAS remote control
-	Brush for lens
- Extender for rc
-	microSD card x 2
-	microSD to SD card converter
- Neck strap
-	Cable: USBC to USB (for connecting iPad to remote control, to solar and external batteries, and to USB wall outlet for charging)
-	Cable: Lightning 8-pin to USB (for connecting iPhone to remote control, to solar and external batteries, and to USB wall outlet for charging)
-	Cable: micro-USB to USB (for connecting solar and external batteries to USB wall outlet for charging and for connecting UAS directly to a computer (if transferring data directly from UAS rather than extracting the SD card and reading it; not recommended, but good to have just in case)
-	Solar battery for phone or iPad charging
-	External battery for phone or iPad charging
-	Computer to read data onto external HD
-	SD card reader 
-	USBC adapter x 2 for external HD and SD card readers
-	External HD x 2 to transfer data after each flight, 3TB each
-	Ground control points x >=15
-	UNAVCO GNSS system equipment for marking GCPs:
    Antennae
    Antennae pole
    Receiver
    Controller
    Cord receiver to antennae
-	GPS for marking GCPs or other boundaries
-	Extra GPS batteries (AA) x a bunch
-	Plastic bags for SD cards
-	Umbrella for shading the screen
-	Notebook
-	Pen/pencil
- Semi-permanent markers for GCP locations (e.g., rebar)


## Equipment needed in fieldhouse:

- iPad charger, just an USB wall outlet (and use same USBC to USB cable as above)
- iPhone charger, just an USB wall outlet (and use same lightning 8-pin to USB cable as above)
- Solar battery charger, just an USB wall outlet (and use same micro-USB to USB cable as above)\
- Charger for remote control and batteries (3 at a time)
- External battery charger - USB wall outlet and micro-USB to USB cable (one included above, so bring a second)
- Computer charger 
- Cable: mini-USB to USB (to connect GPS to computer)
- Cables and charging equipment for UNAVCO GNSS system


## Basics

- Sunscreen
- Water
- Snacks
- Sunglasses
- Hat
- Field clothes


## Maybe also:

- Podium / music stand for computer
- Plywood or other platform for take-off
- Calibration target
- Vest or waist pack
- LRF / measuring tape
