---
title: "MissionChecklist"
authors: "Megan Cattau"
# Add your name above
date: "6/14/2019"
output: md_document
---


# Mission Checklist

This document is a working checklist guide for UAS field missions using the Phantom 4 Pro for forest ecological applications


## Before going into the field (at least day or two before)
- Consult the Flight Planning document for site selection and planning the mission
- Consult the Equipment List and ensure all items are charged
- Contact any landowners / managers as a courtesy and to see if there are wildlife closures that aren’t updated online
- For Cold Springs, Forest Service Permit BOU 512, Use code 422 
Call the Fort Collins Interagency Dispatch Center 970.295.6800 and the Boulder Regional Communication Center 303.441.4444 to let them know that we'll be there (day, time, est location and duration, as well as contact name and info of on-site lead)
- Put out NOTAM: https://www.1800wxbrief.com/Website/uoa - at least 24 hours in advance (Cold Springs is center point of 395851.7N1052815.2W with a radius of .4 miles)

## Field protocol - pre-mission tasks
- Put all UAS eqipment in a shaded spot if possible
- Lay out GCPs distributed throughout the AOI, placing some near the edges of the image and some on the interior in splots where they will be visible in the aerial imagery
- Measure the location of the GCPs and make any notes related to that
- Identify a good launch point and place any landing platform down
- Attach the propellers and make sure they are secure
- Remove the sensor cover from the UAS
- Brush the sensor to clean it
- Check that an SD card is inserted
- Set the UAS on the landing platform
- Check the battery's power and insert it, ensuring it is completely locked in
- Turn on the remote control (push then push and hold) 
- Turn on the UAS after the remote control is on
- Connect the iPhone or iPad to remote control with cable
- Open DJI Go and check the return to home height and any other global setting that are relevant
- Close DJI Go

## Field protocol - Executing the mission
- Consult the Flight Planning Map Pilot document for executing the mission

## Field protocol - post-mission tasks
- Once the UAS has safely landed, turn it off
- Turn off the remote control after the UAS is off
- Close Map Pilot and sleep the tablet if you'd like
- Remove the UAS battery and place it in a shaded spot
- Remove the SD card, replace it with a clean one, and transfer data
- If you are not flying another mission immediately: remove propeller blades and repack them, replace the sensor cover, and repack the UAS
- Once all missions in that AOI are completed, collect the GCPs and replace them with a permanant marker if desired for subsequent missions

## Post-mission tasks at the office
- Fill out CU logbook
- Copy data on external HDs to multiple locations (including S3 buckets)
- Post-process in Agisoft Metashape (see Agisoft Metashape Notes)
- Export data and share with collaborators / feed into further analysis. - Cold Springs: send all footage within one month to Mike Johnson mjohnson10@fs.fed.us
