# Equipment List for UAS Fieldwork

This document is a working list of equipment needed for UAS field expeditions using the Pahntom 4 Pro for forest ecological application

```
Equipment needed in the field: 
-	iPad to operate the mission
-	iPhone as a back-up to operate the mission
-	UAS body
-	UAS batteries x 5
-	Cooler for batteries
-	UAS propeller blades x 8 (4 as back-ups)
-	UAS remote control
-	Brush for lens
-	microSD card x 2
-	microSD to SD card converter
-	Cable: USBC to USB (for connecting iPad to remote control, to solar and external batteries, and to USB wall outlet for charging)
-	Cable: Lightning 8-pin to USB (for connecting iPhone to remote control, to solar and external batteries, and to USB wall outlet for charging)
-	Cable: micro-USB to USB (for connecting solar and external batteries to USB wall outlet for charging and for connecting UAS directly to a computer (if transferring data directly from UAS rather than extracting the SD card and reading it; not recommended, but good to have just in case)
-	Solar battery for phone or iPad charging
-	External battery for phone or iPad charging
-	Computer to read data onto external HD
-	SD card reader 
-	USBC adapter x 2 for external HD and SD card readers
-	External HD x 2 to transfer data after each flight, 3TB each
-	Ground control points x >=15
-	UNAVCO GNSS system equipment for marking GCPs
-	GPS for marking GCPs or other boundaries
-	Extra GPS batteries (AA) x a bunch
-	Plastic bags for SD cards
-	Umbrella for shading the screen
-	Notebook
-	Pen/pencil
```

\pard\pardeftab720\li720\ri0\partightenfactor0
\cf0 \
\pard\pardeftab720\li720\fi-360\ri0\partightenfactor0
\ls2\ilvl0
\f1 \cf0 \'a5	
\f0 Maybe also:\
\pard\pardeftab720\li1440\fi-360\ri0\partightenfactor0
\ls2\ilvl1
\f2 \cf0 o	
\f0 Electricity converters\
\ls2\ilvl1
\f2 o	
\f0 Podium / music stand for computer\
\ls2\ilvl1
\f2 o	
\f0 Plywood or other platform for take-off\
\ls2\ilvl1
\f2 o	
\f0 Calibration target\
\ls2\ilvl1
\f2 o	
\f0 Extender for rc\
\ls2\ilvl1
\f2 o	
\f0 Neck strap\
\ls2\ilvl1
\f2 o	
\f0 Vest or waist pack\
\pard\pardeftab720\ri0\partightenfactor0
\cf0 \
Equipment needed in fieldhouse\
\pard\pardeftab720\li720\fi-360\ri0\partightenfactor0
\ls3\ilvl1
\f1 \cf0 \'a5	
\f0 iPad charger \'96 just an USB wall outlet (and use same USBC to USB cable as above)\
\ls3\ilvl1
\f1 \'a5	
\f0 iPhone charger \'96 just an USB wall outlet (and use same lightning 8-pin to USB cable as above)\
\ls3\ilvl1
\f1 \'a5	
\f0 Solar battery charger \'96 just an USB wall outlet (and use same micro-USB to USB cable as above)\
\ls3\ilvl1
\f1 \'a5	
\f0 Charger for remote control and batteries (3 at a time)\
\ls3\ilvl1
\f1 \'a5	
\f0 External battery charger - USB wall outlet and micro-USB to USB cable (one included above, so bring a second)\
\ls3\ilvl1
\f1 \'a5	
\f0 Computer charger \
\ls3\ilvl1
\f1 \'a5	
\f0 Cable: mini-USB to USB (to connect GPS to computer)\
\ls3\ilvl1
\f1 \'a5	
\f0 Cables and charging equipment for UNAVCO GNSS system\
\pard\pardeftab720\li360\ri0\partightenfactor0
\cf0 \
\pard\pardeftab720\ri0\partightenfactor0
\cf0 \
Basics\
\pard\pardeftab720\li720\fi-360\ri0\partightenfactor0
\ls4\ilvl1
\f1 \cf0 \'a5	
\f0 Sunscreen\
\ls4\ilvl1
\f1 \'a5	
\f0 Water\
\ls4\ilvl1
\f1 \'a5	
\f0 Snacks\
\ls4\ilvl1
\f1 \'a5	
\f0 Sunglasses\
\ls4\ilvl1
\f1 \'a5	
\f0 Hat\
\ls4\ilvl1
\f1 \'a5	
\f0 Field clothes\
}